name: macOS Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env: 
      GH_TOKEN: ${{ secrets.SUBMODULE_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: true
          token: ${{ secrets.SUBMODULE_PAT }}
          
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install submodules
        run: |
          git submodule init 
          git submodule update
          git submodule add https://github.com/giloushaker/nr-shared assets/shared
          
      - name: Install dependencies
        run: npm ci


        

        
      - name: Build application
        run: npm run build
        
      - name: Create macOS release
        run: npx electron-builder --mac --publish=always
        
